#!/bin/bash
set -e

# The workspace lockfile is generated by different pnpm versions in local,
# Replit, and Termux environments. Allow pnpm to reconcile metadata before
# running the post-merge setup instead of failing on a frozen-lockfile check.
pnpm install --no-frozen-lockfile --prefer-offline
pnpm --filter @workspace/db run push
pnpm --filter @workspace/api-server run build
